services:
  # PostgresSQL database
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "trimitgood"         # Set the username
      POSTGRES_PASSWORD: "changeme"     # Set the password
      POSTGRES_DB: "shorty"          # Set the database name

  flyway:
    image: flyway/flyway:11.8.1
    container_name: "flyway-migration"
    command: >
      -url=jdbc:postgresql://db:5432/shorty
      -user=trimitgood
      -password=changeme
      -defaultSchema=sho
      -schemas=sho
      -locations=filesystem:/flyway/migration
      -connectRetries=5
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/migration
    depends_on:
      - db

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
