server:
  port: 8090

spring:
#  defer-datasource-initialization: true
  security:
    user:
      name: showy
      password: showy

  application:
    name: TrimItGood

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # Auto schema creation, can be 'none', 'validate', or 'create'
    show-sql: true
    properties:
      hibernate.format_sql: true
#      hibernate:
#        globally_quoted_identifiers: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: sho
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: false
    validate-on-migrate: true
    out-of-order: false
    target: latest
